name: CleanPLS
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - pytorch
  - gymnasium
  - scikit-image
  - tensorboard
  - tqdm
  - stable-baselines3
  - sb3-contrib
  - pytest
  - jupyter
  - ipykernel
  - sphinx
  - sphinx-rtd-theme
